### ISSUE TITLE
Ambiguity in caching key for the gate cost

### ISSUE THREAD

**Issue by aszady** [qiskit-community/Quantum-Challenge-Grader#2]
This code reuses gate/instruction cost based only on a name and number of qubits. However, one may construct similarly named instruction with its gate cost inherited from the previous one.

https://github.com/qiskit-community/IBMQuantumChallenge2020-Grader/blob/fd231c86d71d6e59d2542085b3abd69329c66b79/qc_grader/util.py#L89

Consider the following example:
```python
from qiskit import QuantumCircuit
from qc_grader.util import compute_cost

q1 = QuantumCircuit(28, 4, name='foo')
print('Subcircuit 1 cost: ', compute_cost(q1))

q2 = QuantumCircuit(28, 4, name='foo')
for _ in range(999):
    q2.ccx(0, 1, 2)
print('Subcircuit 2 cost: ', compute_cost(q2))

qc1 = QuantumCircuit(28, 4)
qc1.append(q1, range(28), range(4))
print('Circuit 1 cost: ', compute_cost(qc1))

qc2 = QuantumCircuit(28, 4)
qc2.append(q2, range(28), range(4))
print('Circuit 2 cost: ', compute_cost(qc2), '<-- PROFIT')
```

Returning:
```
Computing cost...
Subcircuit 1 cost:  0
Computing cost...
Subcircuit 2 cost:  68931
Computing cost...
Circuit 1 cost:  0
Computing cost...
Circuit 2 cost:  0 <-- PROFIT
```

Combined with https://github.com/qiskit-community/IBMQuantumChallenge2020-Grader/issues/1 it leads to unreliability of the ranking.

**Comment by HuangJunye** [comment]
@aszady Thanks for reporting this bug. Adding the name indeed will make the cost become 0. It might be too late to modify the grader as many participants have submitted their solutions. We will manually check at least the top 10 solutions and use Unroller to verify that the cost is accurate. We used this method to compute cost because for a large circuits Unrolling can take minutes.

**Comment by vabarbosa** [comment]
this issue is being  closed because it has been inactive
